In [34]:
import numpy as np
import pandas as pd
data1=np.random.randint(3,10,5)
print(data1)

[5 8 3 5 7]


In [35]:
s1=pd.Series(data1,index=['a','b','c','d','e'])
print(s1)

a    5
b    8
c    3
d    5
e    7
dtype: int32


In [37]:
s1[2:5]

c    3
d    5
e    7
dtype: int32

In [39]:
s1['c':'e']

c    3
d    5
e    7
dtype: int32

In [41]:
dict1={'year':np.arange(2017,2020),'price':[10,20,30]}
pd.DataFrame(dict1,index=[0,1,2])

year  price
0  2017     10
1  2018     20
2  2019     30

In [44]:
data2=np.random.randint(5,15,[5,3])
print(data2)

[[10  5  7]
 [ 8 12 12]
 [12  5  7]
 [10 11  7]
 [ 8 13 10]]


In [47]:
df_text=pd.DataFrame(data2,index=['a','c','e','f','h'],columns=['one','two','three'])
print(df_text)

   one  two  three
a   10    5      7
c    8   12     12
e   12    5      7
f   10   11      7
h    8   13     10


In [61]:
df_text.loc['a','one']=''
df_text.loc['c','two']=-99
df_text.loc['c','three']=-99
df_text.loc['a','two']=-100
df_text['four']='test'
df_change=df_text.reindex(['a','b','c','d','e','f','g','h'])
print(df_change)

   one    two  three  four
a      -100.0    7.0  test
b  NaN    NaN    NaN   NaN
c    8  -99.0  -99.0  test
d  NaN    NaN    NaN   NaN
e   12    5.0    7.0  test
f   10   11.0    7.0  test
g  NaN    NaN    NaN   NaN
h    8   13.0   10.0  test


In [62]:
df_change.dropna()

one    two  three  four
a     -100.0    7.0  test
c   8  -99.0  -99.0  test
e  12    5.0    7.0  test
f  10   11.0    7.0  test
h   8   13.0   10.0  test

In [63]:
df_change.dropna(how='all')

one    two  three  four
a     -100.0    7.0  test
c   8  -99.0  -99.0  test
e  12    5.0    7.0  test
f  10   11.0    7.0  test
h   8   13.0   10.0  test

In [64]:
df_change.fillna(0)

one    two  three  four
a     -100.0    7.0  test
b   0    0.0    0.0     0
c   8  -99.0  -99.0  test
d   0    0.0    0.0     0
e  12    5.0    7.0  test
f  10   11.0    7.0  test
g   0    0.0    0.0     0
h   8   13.0   10.0  test

In [65]:
df_change.drop_duplicates()

one    two  three  four
a      -100.0    7.0  test
b  NaN    NaN    NaN   NaN
c    8  -99.0  -99.0  test
e   12    5.0    7.0  test
f   10   11.0    7.0  test
h    8   13.0   10.0  test